---

isucon:
  hosts:
    instance1:
      ansible_host: "{{ instance1_public_ip }}"
      ansible_user: "{{ instance_user }}"
      ansible_ssh_private_key_file: "{{ instance_ssh_private_key_file }}"
    instance2:
      ansible_host: "{{ instance2_public_ip }}"
      ansible_user: "{{ instance_user }}"
      ansible_ssh_private_key_file: "{{ instance_ssh_private_key_file }}"
    instance3:
      ansible_host: "{{ instance3_public_ip }}"
      ansible_user: "{{ instance_user }}"
      ansible_ssh_private_key_file: "{{ instance_ssh_private_key_file }}"
